# Generated by Django 5.1.4 on 2025-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0003_waitercall'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
