# Generated by Django 5.1.4 on 2025-01-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0004_category_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
