# Generated by Django 5.1.4 on 2025-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0013_order_discount_order_final_total_order_gst_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
