# Generated by Django 5.1.4 on 2025-01-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0014_alter_order_final_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
