# Generated by Django 5.1.4 on 2025-01-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0015_alter_order_final_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
