# Generated by Django 5.1.4 on 2025-01-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0017_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gst_rate',
        ),
        migrations.AddField(
            model_name='order',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
    ]
