# Generated by Django 5.1.4 on 2025-01-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0018_remove_order_gst_rate_order_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
