# Generated by Django 5.1.4 on 2025-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0019_alter_category_sort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
