# Generated by Django 5.1.4 on 2025-02-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0022_remove_orderitem_status_orderitem_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
