# Generated by Django 5.1.4 on 2025-03-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0027_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='preferences',
            new_name='notes',
        ),
    ]
