# Generated by Django 5.1.4 on 2025-04-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0029_order_user_order_id_alter_order_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gpay', 'GPay'), ('card', 'Credit Card'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_order_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
