# Generated by Django 5.1.4 on 2025-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0036_add_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
