# Generated by Django 5.1.4 on 2025-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0038_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_display_mode',
            field=models.CharField(choices=[('grid', 'Grid View (All items)'), ('category_first', 'Category First View')], default='grid', max_length=20),
        ),
    ]
