# Generated by Django 5.1.4 on 2025-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0040_alter_order_status_alter_profile_menu_display_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='_payment_methods',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
