# Generated by Django 5.1.4 on 2025-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmenu_app', '0041_remove_order_payment_method_order__payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_amounts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
